### PR TITLE
Create home for vro-plugin-user

### PR DESCRIPTION
**Pull request by alvagante**
It looks like we need the home for the vro-plugin-user to be able to retrieve the list of environments and roles from the PE server:

Logs from the Orchestrator

```
2017-05-24 09:32:20.133+0000 vco: [component="SCRIPTING_LOG" priority="INFO" thread="http-nio-127.0.0.1-8280-exec-4" user="configurationadmin@vsphere.local" context="" token="" wfid="" wfname="" anctoken="" wfstac
k="" instanceid=""] [script: com.puppet.o11n.plugin.puppet/getEnvironments] (com.puppet.o11n.plugin.puppet/getEnvironments) Looking up environments on puppet.mgmt.infocert.it
2017-05-24 09:32:20.186+0000 vco: [component="ScriptModuleRuntimeServiceImpl" priority="WARN" thread="http-nio-127.0.0.1-8280-exec-4" user="" context="" token="" wfid="" wfname="" anctoken="" wfstack="" instanceid
=""] Unable to execute action class ch.dunes.util.DunesServerException: Failed to get list of environments from master. exitCode=0 error=Could not chdir to home directory /home/vro-plugin-user: No such file or dir
ectory
 (unnamed script#31)
2017-05-24 09:32:20.186+0000 vco: [component="BaseController" priority="ERROR" thread="http-nio-127.0.0.1-8280-exec-4" user="" context="" token="" wfid="" wfname="" anctoken="" wfstack="" instanceid=""] Error invo
king REST [unknown]
ch.dunes.util.DunesServerException: Action 'getEnvironments' in module 'com.puppet.o11n.plugin.puppet' failed : Failed to get list of environments from master. exitCode=0 error=Could not chdir to home directory /h
ome/vro-plugin-user: No such file or directory
 (unnamed script#31)
        at com.vmware.o11n.service.impl.ScriptModuleRuntimeServiceImpl.executeServerAction(ScriptModuleRuntimeServiceImpl.java:58)
        at c

```

### CODE REVIEW

**Comment by jpadams** [comment]
@alvagante What operating system are you on?

**Comment by jpadams** [comment]
I've heard this as an issue on CentOS 6 and maybe SLES.

**Comment by alvagante** [comment]
@jpadams CentOS 7

**Comment by jpadams** [comment]
Post Script: We weren't experiencing the issue with homedir in CI or manual tests, but then heard other users were. Originally we wanted the vro-plugin-user to be very "service account-like" so we didn't give it a homedir. Turns out enough people needed it, that it made sense to enable it for this reference implementation.

**Pull request merged**
