### PR TITLE
Update readme with links to full vRO documentation.

### PR DESCRIPTION
**Pull request by tylerpace**
- Update README with a link to the full plugin documentation.
- Restructure readme just a bit to use headings.

### CODE REVIEW

**Comment by tylerpace** [comment]
Ping @maju6406 @jpadams @gguillotte

**Comment by tylerpace** [comment]
This PR potentially fulfills https://tickets.puppetlabs.com/browse/CLOUD-813

**Comment by gguillotte** [comment]
I'm :+1: but mind that the docs link won't work until its PR is approved and merged, and the docs site is rebuilt with it. Ideally we'd merge this after that page is live.

**Comment by maju6406** [comment]
@gguillotte @tylerpace the readme instructions will need to be updated once this PR is merged https://github.com/puppetlabs/puppet-vro-starter_content/pull/11

Alternatively, we could trash this PR and I could incorporate @tylerpace's changes into my PR

**Pull request closed without merging**
