### PR TITLE
Implement a Hiera 5 environment hiera.yaml file

### PR DESCRIPTION
**Pull request by reidmv**
Reverts bc6789926fdcb48df26d762caeba621d900b1adf.

This new in-environment hiera.yaml configures where the environment expects data to be found. The vRO starter content repo in particular is dependent on the common.yaml it contains, so it's a good idea to make sure automatic parameter lookups are actually consulting that file.

In previous versions of Puppet the default out-of-box global hierarchy happened to ingest this file. With the advent of Hiera 5 though, that changes, and it is expected that a Puppet environment will self-reference data it needs or expects via its own hiera.yaml (the global hiera.yaml is now just an override).p

### CODE REVIEW

**Comment by reidmv** [comment]
@jpadams ^^

**Comment by jpadams** [comment]
@reidmv Do we also need to keep the hieradata directory with the same contents so that a legacy 2016.4 master can get at the common.yaml with the default global hiera.yaml file? Or is hiera5 compatible environment data going to just work?

**Comment by reidmv** [comment]
Hiera 5 has been in the LTS since 2016.4.6.

As long as the version being used is 2016.4.6 or newer, this should work for both the LTS and STS PE versions.

For versions 2016.4.5 and older, this would require a global hiera.yaml change to work because of the directory name change.

@jpadams tl;dr is, this PR would make 2016.4.6 or newer a prerequisite.

**Comment by jpadams** [comment]
@reidmv I guess we don't need the `hieradata` dir if we assume that we only support latest Z of LTS. In that case users will be at Puppet 4.10 and thus have Hiera 5. https://puppet.com/docs/pe/2016.4/overview_version_table.html#puppet-enterprise-2016x

**Comment by jpadams** [comment]
yup yup

**Pull request merged**
